name: serv_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'   # relax a bit—avoids unnecessary conflicts

dependencies:
  flutter:
    sdk: flutter

  # UI & system
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0
  table_calendar: ^3.0.9
  image_picker: ^1.1.2
  image_picker_web: ^3.1.1
  file_picker: ^8.1.2
  open_filex: ^4.5.0
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.5
  intl: ^0.20.2
  google_maps_flutter: ^2.9.0
  intl_phone_field: ^3.2.0
  permission_handler: ^11.3.1
  universal_io: ^2.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1

  # Camera & ML Kit (ONLY split packages)
  camera: ^0.11.0
  path_provider: ^2.1.4
  path: ^1.9.0
  google_mlkit_selfie_segmentation: 0.10.0
  google_mlkit_object_detection: 0.15.0
  google_mlkit_pose_detection: 0.14.0
  image_gallery_saver_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_28pt-Italic.ttf
          style: italic
