name: serv_app
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & System packages
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  image_picker_web: ^2.1.1
  file_picker: ^10.2.0
  open_filex: ^4.7.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.0
  intl: ^0.20.2
  google_maps_flutter: ^2.5.0
  intl_phone_field: ^3.2.0
  permission_handler: ^12.0.1
  universal_io: ^2.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  image_gallery_saver: ^2.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.4.0
  geolocator: ^14.0.2
  url_launcher: ^6.2.1
  




  # Face detection and camera
  camera: ^0.10.0+4
  google_ml_kit: ^0.13.0
  path_provider: ^2.0.12
  path: ^1.8.0

    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Add this only if you use image assets

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_28pt-Italic.ttf
          style: italic




   
